--external-downloader aria2c
--external-downloader-args aria2c:"-x 16 -s 8 -k 1M"
--remote-components ejs:github
--concurrent-fragments 16
--embed-thumbnail
--embed-metadata
-f "bestvideo*[height<=1440]+bestaudio/best"
# --cookies-from-browser firefox
